import { z } from "zod";

export const fdSchema = z.object({
  instrument_type: z.string().min(1),
  holder_name: z.string().min(1),
  bank_name: z.string().min(1),
  branch: z.string().min(1),
  fd_number: z.string().min(1),
  deposit_date: z.string().min(10),
  maturity_date: z.string().min(10),
  principal: z.coerce.number().positive(),
  interest_rate: z.coerce.number().positive(),
  payout_type: z.string().min(1),
  status: z.string().min(1),
  funding_type: z.string().min(1),
  renewal_from_fd_id: z.coerce.number().optional(),
  linked_loan_id: z.coerce.number().optional(),
  reserved_for: z.string().optional(),
  incentive_expected: z.coerce.number().optional(),
  incentive_received: z.coerce.number().optional(),
  certificate_received: z.coerce.number().optional(),
  certificate_received_date: z.string().optional(),
  raised_by_name: z.string().optional(),
  raised_by_contact: z.string().optional(),
  raised_under_name: z.string().optional(),
  nominee_name: z.string().optional(),
  remarks: z.string().optional(),
  notes: z.string().optional(),
});

export const loanSchema = z.object({
  loan_type: z.string().min(1),
  holder_name: z.string().min(1),
  bank_name: z.string().min(1),
  account_number: z.string().min(1),
  start_date: z.string().min(10),
  end_date: z.string().min(10),
  principal_amount: z.coerce.number().positive(),
  interest_rate: z.coerce.number().positive(),
  repayment_type: z.string().min(1),
  emi_amount: z.coerce.number().optional(),
  outstanding_principal: z.coerce.number().min(0),
  bullet_closure_amount: z.coerce.number().optional(),
  status: z.string().min(1),
  notes: z.string().optional(),
});

export const rdSchema = z.object({
  holder_name: z.string().min(1),
  bank_name: z.string().min(1),
  branch: z.string().min(1),
  rd_number: z.string().min(1),
  start_date: z.string().min(10),
  maturity_date: z.string().min(10),
  monthly_installment: z.coerce.number().positive(),
  total_installments: z.coerce.number().int().positive(),
  installments_paid: z.coerce.number().int().min(0),
  interest_rate: z.coerce.number().positive(),
  status: z.string().min(1),
  reserved_for: z.string().optional(),
  notes: z.string().optional(),
});

export const bondSchema = z.object({
  platform: z.string().min(1),
  issuer_name: z.string().min(1),
  bond_name: z.string().min(1),
  isin: z.string().min(6),
  holder_name: z.string().min(1),
  investment_date: z.string().min(10),
  maturity_date: z.string().min(10),
  principal_invested: z.coerce.number().positive(),
  face_value: z.coerce.number().positive(),
  coupon_rate: z.coerce.number().positive(),
  payout_frequency: z.string().min(1),
  payout_day: z.coerce.number().int().min(1).max(31),
  units: z.coerce.number().positive(),
  status: z.string().min(1),
  notes: z.string().optional(),
});

export const epfSchema = z.object({
  employer_name: z.string().min(1),
  uan: z.string().min(1),
  member_id: z.string().min(1),
  current_balance: z.coerce.number().min(0),
  employee_monthly: z.coerce.number().min(0),
  employer_monthly: z.coerce.number().min(0),
  interest_rate: z.coerce.number().min(0),
  last_interest_credit_date: z.string().min(10),
  status: z.string().min(1),
  notes: z.string().optional(),
});

export const ppfSchema = z.object({
  bank_name: z.string().min(1),
  account_number: z.string().min(1),
  holder_name: z.string().min(1),
  start_date: z.string().min(10),
  maturity_date: z.string().min(10),
  extension_years: z.coerce.number().int().min(0),
  current_balance: z.coerce.number().min(0),
  contribution_this_fy: z.coerce.number().min(0),
  target_contribution_fy: z.coerce.number().min(0),
  fy_deadline_date: z.string().min(10),
  last_contribution_date: z.string().optional(),
  status: z.string().min(1),
  notes: z.string().optional(),
});

export const insuranceSchema = z.object({
  policy_type: z.string().min(1),
  insurer_name: z.string().min(1),
  policy_number: z.string().min(1),
  holder_name: z.string().min(1),
  sum_assured: z.coerce.number().positive(),
  premium_amount: z.coerce.number().positive(),
  premium_frequency: z.string().min(1),
  next_due_date: z.string().min(10),
  grace_days: z.coerce.number().int().min(0),
  start_date: z.string().min(10),
  end_date: z.string().optional(),
  nominee_name: z.string().optional(),
  status: z.string().min(1),
  notes: z.string().optional(),
});

export const physicalAssetSchema = z.object({
  asset_type: z.string().min(1),
  asset_name: z.string().min(1),
  holder_name: z.string().min(1),
  quantity: z.coerce.number().positive(),
  unit: z.string().min(1),
  purchase_date: z.string().min(10),
  purchase_rate: z.coerce.number().positive(),
  current_rate: z.coerce.number().positive(),
  status: z.string().min(1),
  notes: z.string().optional(),
});
